/***********************************************************************************
 * Class Name : Constants
 * Created By : Azarudeen (Exafort)
 -----------------------------------------------------------------------------------
 * Description : Class used to store all the static text being used in the Quote
                 template custom section VF pages and classes
 -----------------------------------------------------------------------------------
 * Version History:
 * Version      Developer Name      Date            Detail Features
 * 1.0          Azarudeen        04-10-2020       Initial Development
 **********************************************************************************/
public class Constants {

    public static String QID = 'qid';
    public static String SUBSCRIPTIONFEES = 'SUBSCRIPTION FEES';
    public static String PRODUCTS = 'PRODUCTS';
    public static String QTY = 'QTY';
    public static String ANNUALLISTRATE = 'ANNUAL LIST RATE';
    public static String DISCOUNT = 'DISCOUNT APPLIED';
    public static String ONETIMEDISCOUNT = 'ONE-TIME DEDUCTION';
    public static String PARTNERDISCOUNT = 'PARTNER DISCOUNT';
    public static String ANNUALEFFECTIVERATE = 'ANNUAL EFFECTIVE RATE';
    public static String TERM = 'TERM';
    public static String LINETOTAL = 'TOTAL TERM';
    public static String SUBSCRIPTIONTOTALFEES = 'Subscription Service Total Fees, ';
    public static String LISTRATE = 'LIST RATE';
    public static String ONETIMEFEES = 'ONE-TIME FEES';
    public static String LICENSETOTALFEES = 'Non-Subscription Services Total Fees, ';
    public static String QUOTETOTAL = 'Order Total, ';
    public static string ADDITIONALSUBSCRIPTIONFEES = 'ADDITIONAL SUBSCRIPTION FEES';
    public static string PROFSERVICESONETIMEFEES = 'PROFESSIONAL SERVICES ONE-TIME FEES';
    public static string OTHERONETIMEFEES = 'OTHER ONE-TIME FEES';
    
    //Adding few more static texts used on the VF content section related to display the Billing Schedules
    public static String INVOICENUMBER = 'INVOICE NUMBER';
    public static String INVOICEDATE = 'INVOICE DATE';
    public static String SERVICESTART = 'SERVICE START DATE';
    public static String SERVICEEND = 'SERVICE END DATE';
    public static String SUBSCRIPTIONAMOUNT = 'SUBSCRIPTION FEES';
    public static String INVOICETOTAL = 'INVOICE TOTAL';
    public static String PAYMENTSCHEDULES = 'BILLING SCHEDULES';
    public static String PAYMENTSCHEDULEDESC = 'Below is the expected payment schedule for this Order Form.  Please refer to the applicable issued invoices for exact dates and details.';
}