public class CPQBillingScheduleParameters {

    public Date startDate {get; set;}
    public Date endDate {get; set;}
    public Decimal term {get; set;}
    public Decimal billingFrequency {get; set;}
    public Integer numberOfInvoices {get; set;}
    public Decimal subscriptionTotal {get; set;}
    public Decimal oneTimeTotal {get; set;}
    public Decimal subscriptionMonthlyRate {get; set;}
    public Decimal mrr {get; set;}
}